use cadastro;
show tables;
select * from gafanhotos order by nome;
select * from cursos order by nome desc;
select nome, carga, ano from cursos order by ano, nome;
select * from cursos where ano ='2016' order by nome;
select nome, carga from cursos where ano ='2016' order by nome;
select nome, descricao, ano from cursos where ano <= 2016 order by ano, nome;
select nome, ano from cursos where ano between 2014 and 2016 order by ano, nome;
select nome, ano from cursos where ano in (2014, 2017) order by ano, nome;
select nome, carga, totaulas from cursos where carga > 30 and totaulas < 30 order by nome;
select nome, carga, totaulas from cursos where carga > 30 or totaulas < 30 order by nome;